[phases.setup]
nixPkgs = ["python310"]

[phases.install]
cmds = ["cd 'Reddit Ovarra' && pip install -r requirements.txt"]

[start]
cmd = "cd 'Reddit Ovarra' && uvicorn main:app --host 0.0.0.0 --port $PORT"
