[build]
builder = "NIXPACKS"
buildCommand = "cd 'Reddit Ovarra' && pip install -r requirements.txt"

[deploy]
startCommand = "cd 'Reddit Ovarra' && uvicorn main:app --host 0.0.0.0 --port $PORT"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
